name: Create Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
      - name: Grant Permission to Execute
        run: chmod +x gradlew
      - name: Publish Library
        env:
          artifactoryUser: ${{ secrets.ARTIFACTORY_USER }}
          artifactoryPwd: ${{ secrets.ARTIFACTORY_PWD }}
          bintrayVersionName: ${{ github.ref }}
        run: ./gradlew publish
